string(TIMESTAMP BUILD_DATE "%d.%m.%Y")

set(C_COMPILER_INFO "${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION}")

execute_process(
    COMMAND ${CMAKE_ASM_NASM_COMPILER} -v
    OUTPUT_VARIABLE NASM_VERSION_OUTPUT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

string(REGEX MATCH "^([^ ]+ [^ ]+ [^ ]+)" NASM_COMPILER_INFO "${NASM_VERSION_OUTPUT}")

target_compile_definitions(kernel PRIVATE
    BUILD_DATE="${BUILD_DATE}"

    C_COMPILER_INFO="${C_COMPILER_INFO}"
    NASM_COMPILER_INFO="${NASM_COMPILER_INFO}"

    ARCH_NAME="${ARCH}" 
)