if(ARCH STREQUAL "i386")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m32 -ffreestanding -fno-pie -fno-stack-protector -fno-builtin -nostdlib -mno-red-zone -Wall -Wextra" CACHE STRING "" FORCE)
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -no-pie -nostdlib" CACHE STRING "" FORCE)

    set(CMAKE_ASM_FLAGS "-f elf32" CACHE STRING "" FORCE)
    set(CMAKE_ASM_NASM_OBJECT_FORMAT "elf32" CACHE STRING "" FORCE)
    set(CMAKE_ASM_NASM_FLAGS "${CMAKE_ASM_NASM_FLAGS} -f elf32" CACHE STRING "NASM flags" FORCE)
elseif(ARCH STREQUAL "x86_64")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m64 -ffreestanding -fno-pie -fno-stack-protector -fno-builtin -nostdlib -mno-red-zone -Wall -Wextra" CACHE STRING "" FORCE)
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -no-pie -nostdlib" CACHE STRING "" FORCE)

    set(CMAKE_ASM_FLAGS "-f elf64" CACHE STRING "" FORCE)
    set(CMAKE_ASM_NASM_OBJECT_FORMAT "elf64" CACHE STRING "" FORCE)
    set(CMAKE_ASM_NASM_FLAGS "${CMAKE_ASM_NASM_FLAGS} -f elf64" CACHE STRING "NASM flags" FORCE)
else()
    message(FATAL_ERROR "Unsupported architecture: ${ARCH}. Use i386 or x86_64.")
endif()