set(CMAKE_SYSTEM_NAME Generic)

set(CMAKE_C_COMPILER gcc)
find_program(NASM_PATH nasm REQUIRED)
set(CMAKE_ASM_NASM_COMPILER ${NASM_PATH})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)